# Generated by Django 4.0.6 on 2022-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='age',
            field=models.CharField(default='', max_length=3),
        ),
    ]
