# Generated by Django 4.0.6 on 2022-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0002_candidat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
