# Generated by Django 4.0.6 on 2022-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0005_candidat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuver', 'Approuver'), ('Desapprouver', 'Desapprouver')], default='En attente', max_length=50, null=True),
        ),
    ]
