# Generated by Django 4.0.6 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0006_alter_candidat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('Attente', 'Attente'), ('Approuver', 'Approuver'), ('Desapprouver', 'Desapprouver')], default='Attente', max_length=50, null=True),
        ),
    ]
