# Generated by Django 4.0.6 on 2022-09-21 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0007_alter_candidat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='experience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='fumeur',
            field=models.CharField(choices=[('1', 'Oui'), ('2', 'Non')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candidat',
            name='genre',
            field=models.CharField(default=datetime.datetime(2022, 9, 21, 12, 10, 24, 733484, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='personnality',
            field=models.CharField(choices=[('', 'Choisissez votre personnalité'), ('Je suis agile', 'Je suis agile'), ('Je suis ambitieux', 'Je suis ambitieux'), ('Je suis sournois', 'Je suis sournois'), ('Je suis pathetique', 'Je suis pathetique'), ('Je suis absentheiste', 'Je suis absentheiste')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='salaire',
            field=models.CharField(default=datetime.datetime(2022, 9, 21, 12, 11, 1, 393682, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
