# Generated by Django 4.0.6 on 2022-09-23 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0008_candidat_experience_candidat_fumeur_candidat_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='fichier',
            field=models.FileField(default=datetime.datetime(2022, 9, 23, 13, 34, 27, 596686, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='personnality',
            field=models.CharField(choices=[('Je suis agile', 'Je suis agile'), ('Je suis ambitieux', 'Je suis ambitieux'), ('Je suis sournois', 'Je suis sournois'), ('Je suis pathetique', 'Je suis pathetique'), ('Je suis absentheiste', 'Je suis absentheiste')], max_length=200, null=True),
        ),
    ]
